spring:
  application:
    name: product_auction

  datasource:
    url: jdbc:postgresql://localhost:5432/product_auction_db
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update  # ?? none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true

server:
  port: 8082
