spring:
  application:
    name: product_auction-dev

  datasource:
    url: jdbc:postgresql://localhost:5432/product_auction_dev_db  # 개발 DB URL
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서는 ddl-auto: update 설정
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
