spring:
  application:
    name: product_auction-dev

  datasource:
    url: jdbc:postgresql://localhost:5432/product_auction_dev_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL Dialect 추가
        format_sql: true
        use_sql_comments: true
    show-sql: true

server:
  port: 8082  # 개발 서버 포트 설정
